services:

  mysql:
    container_name: mysql
    image: mysql/mysql-server:8.0.26
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: orders
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
  
  ordersystem:
    container_name: ordersystem
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
      - cmd/ordersystem/.env
    volumes:
      - ./cmd/ordersystem/.env:/app/.env
    ports:
      - "${WEB_SERVER_PORT:-8000}:8000"
      - "${GRPC_SERVER_PORT:-50051}:50051"
      - "${GRAPHQL_SERVER_PORT:-8080}:8080"